services:
  - type: web
    name: my-konnect-backend
    env: docker
    dockerfilePath: ./backend/Dockerfile

  - type: web
    name: my-konnect-frontend
    env: docker
    dockerfilePath: ./frontend/Dockerfile
